@host = http://localhost:8000/api/v1

### Get history
GET {{host}}/stocks/history
Content-Type: application/json
Accept: application/json

{
    "product_id": 1,
    "warehouse_id": 1,
    "period_start": "2025-03",
    "period_end": "2025-04"
}