### Post order 1
POST http://maxmollcrm/api/v1/order
Content-Type: application/json
Accept: application/json

{
    "customer": "Demo User 1",
    "items" : [{"id": 1, "count": 1}, {"id": 2, "count": 1}]
}

### Post order 2
POST http://maxmollcrm/api/v1/order
Content-Type: application/json
Accept: application/json

{
    "customer": "Demo User 2",
    "items" : [{"id": 6, "count": 1}]
}

### Resume order
PUT http://maxmollcrm/api/v1/order/resume
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Cancel order
PUT http://maxmollcrm/api/v1/order/cancel
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Complete order
PUT http://maxmollcrm/api/v1/order/complete
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Update order 1
PUT http://maxmollcrm/api/v1/order
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "customer": "Demo User 1_1",
    "items" : [{"id": 4, "count": 3}]
}

### Update order 2
PUT http://maxmollcrm/api/v1/order
Content-Type: application/json
Accept: application/json

{
    "id": 2,
    "customer": "Demo User 2_1",
    "items" : [{"id": 1, "count": 2}, {"id": 2, "count": 3},{"id": 4, "count": 4}]
}