@host = http://localhost:8000/api/v1

### Post order 1
POST {{host}}/order
Content-Type: application/json
Accept: application/json

{
    "customer": "Demo User 1",
    "items" : [{"id": 1, "count": 1}, {"id": 2, "count": 1}]
}

### Post order 2
POST {{host}}/order
Content-Type: application/json
Accept: application/json

{
    "customer": "Demo User 2",
    "items" : [{"id": 3, "count": 3}]
}

### Resume order
PUT {{host}}/order/resume
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Resume order (another version)
GET {{host}}/order/1/resume
Content-Type: application/json
Accept: application/json

### Cancel order
PUT {{host}}/order/cancel
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Cancel order (another version)
GET {{host}}/order/1/cancel
Content-Type: application/json
Accept: application/json

### Complete order
PUT {{host}}/order/complete
Content-Type: application/json
Accept: application/json

{
    "id": 1
}

### Complete order (another version)
GET {{host}}/order/1/complete
Content-Type: application/json
Accept: application/json

### Update order 1
PUT {{host}}/order
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "customer": "Demo User 1_1",
    "items" : [{"id": 1, "count": 2}]
}

### Update order 2
PUT {{host}}/order
Content-Type: application/json
Accept: application/json

{
    "id": 2,
    "customer": "Demo User 2_1",
    "items" : [{"id": 2, "count": 2}]
}